### ISSUE TITLE
Add to Linux marketplace!

### ISSUE THREAD

**Issue by ineedpr0xy** [SoftEtherVPN/SoftEtherVPN#111]
"apt-get install softethervpn"

Cons:
Easy to maintain, easy to update latest version

Pros:
None

Please do it!!

**Comment by NoahO** [comment]
Also, automatic verification of the hash of the installer adds security!

**Comment by chipitsine** [comment]
you can do something like that using 

https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn/+packages

**Comment by NoahO** [comment]
This is a far cry from an official build submitted to eg the debian or ubuntu repositories..

**Comment by chipitsine** [comment]
Why?

**Comment by BlackHoleFox** [comment]
The current method requires adding a PPA manually and trusting that third party source. The proposed method is direct publications from this repository into a default base, such as the Debian Universe package repository.

**Comment by paskal** [comment]
Including package to Ubuntu mean including it first to Debian. Including new package to Debian is a hard work, and even bigger work is maintaining it up-to-date in there. I don't think it will happen in the near or distant future, in last 4 years noone interested in getting it done done anything to actually make it happen, PPA is the best thing I could come with.

**Comment by NoahO** [comment]
Thanks, and I appreciate the effort that has been put into the PPA, it certainly makes it a lot easier for most people 👍 

Consider this just a feature request, if somebody has time. I think it could be good for adoption, because most people that look for VPN software are wary about security - and to tell them "hey, just download this software you haven't heard of before from github/launchpad", it takes a different trust level than saying - hey, it's part of ubuntu, install it through apt-get / software center.
