### ISSUE TITLE
Cipher Order options

### ISSUE THREAD

**Issue by ThomasTrain** [SoftEtherVPN/SoftEtherVPN#1197]
We need to add a option or capability for cipher ordering.

While the config file does offer a 'preferred primary cipher', when scanning the running server, other ciphers are also presented and they are presented in the default openssl order presentation and this results in failing grades on vulnerability and configuration scanners.

We need an option added to the config file similar to how nginx and apache to use preferred cipher order that orders the strongest ciphers first and weakest ciphers last.

**Comment by domosekai** [comment]
This feature is actually implicitly supported. You can enter a cipher list instead of a single cipher. The list should use OpenSSL format.
For example,
ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
