### ISSUE TITLE
[SECURITY ALERT] Stop sending computer information WITHOUT user say so!!

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#120]
The problem is, this VPN software and the client(SEVPN Client, PacketixVPN Client) are leaking,
but not limited to:

2014-12-XX XX:XX:49.123 Session "SID-YYYYY-2": VPN Client details: (
Client product name: "SoftEther VPN Client",
Client version: XXXX,  <------HEY SECLIENT! DONT SEND IT!!
Client build number: XXXX,  <------HEY SECLIENT! DONT SEND IT!!
Server product name: "SoftEther VPN Server (64 bit)",
Server version: 1234,
Server build number: 5678,

Client OS name: "Windows FUCKYOU",  <------HEY SECLIENT! DONT SEND IT!!
Client OS version: "Build 1234, Multiprocessor Free, Service FUCK 1 (1234.XXX.XX-XX)",  <------HEY SECLIENT! DONT SEND IT!!
Client product ID: "--",  <------HEY SECLIENT! DONT SEND IT!!
Client host name: "YYYYY",  <------HEY SECLIENT! DONT SEND IT!!
Client IP address: "LOCALIP.123",  <------HEY SECLIENT! DONT SEND IT!!
Client port number: 12345,
Server host name: "LOCALIP.456/tcp",
Server IP address: "LOCALIP.456",
Server port number: 1234,
Proxy host name: "",
Proxy IP address: "0.0.0.0",
Proxy port number: 0,
Virtual Hub name: "WTF",
Client unique ID: "XXXXXXXXXXXXXXXX")

So, stop sending these.
Seriously, your VPN software leak too much.
(Packet logging shows other information too, I hope other people look into it, like me!!)

DO NOT TRUST OPEN SOURCE.
YOU CAN TRUST IT ONLY YOU READ/VERIFY THE FUCKIN' CODE!

Related;
https://twitter.com/esetglobal/status/545273531089817600/photo/1

A company which use SEVPN says:
"Hey this guy's PC name is 'iluvp0rn'. Let's call a fucking police!!"

I have NO IDEA WHY THIS VPN SOFTWARE SEND A COMPUTER NAME AND VERSION.

YOU MUST HIDE VERSION, OR LET USER TO HIDE VERSION. (LIKE APACHE or PHP. JUST ADD AN OPTION!)
YOU MUST NOT TELL VERSION TO A HACKER. THIS IS A SECURITY ISSUE.

**Comment by Cattze2015** [comment]
SoftetherVPN and PacketixVPN are both comes with tracking.
They send your computer name, local IP address to VPN server.
Sometimes, these information goes to EDUCATION network in South Asia.

http://www.makeuseof.com/tag/antivirus-tracking-youd-surprised-sends/
^ What's the difference between this evil AV and SEVPN? Same!

Hey @dnobori, any comments?
At least, "Computer name" and "OS type/version/serial" should not be sent to VPN server(including PacketixVPN).
Your VPN Client sent too much information. Can't you make it minimum?

**Comment by Owyn** [comment]
At least VPN server can't sniff what sites you visit and your usernames and passwords sent to http websites, can it? /sarcasm ... or not?

**Comment by yurivict** [comment]
If such security concerns aren't addressed for 3 months, people probably shouldn't use SoftEtherVPN at all.

**Comment by meganerd** [comment]
There are some valid concerns (like computername, OS name and version for
instance).  Others are limitations of TCP/IP, such as the the client IP
which is already in the TCP headers (so hiding it here does not get you
anything).  The hostname should be visible to anyone capable of doing a DNS
and whois lookup on the client IP.

You should manage your expectations about what a VPN can do for you.  VPNs
do not get you privacy, at best they obscure your traffic to the VPN server
though you are still vulnerable to traffic pattern analysis and timing
attacks.

Since this is open source, you could probably start by submitting some
patches.  Just sayin'.

**Comment by yurivict** [comment]
No, TCP itself doesn't send your local IP address. TCP only sends minimal info actually.

The argument "hey, this is open source, just contribute" only goes that far. Open source projects have to have strong authorities who integrate patches and drive development.

In this case security concern isn't addressed for 3 months. In another bug report I asked why some obscure error occurs, and also no answer.

Open source project can not function only driven by contributors.

**Comment by meganerd** [comment]
On Wed, Mar 11, 2015 at 4:54 PM, yurivict <notifications@github.com> wrote:

> No, TCP itself doesn't send your local IP address. TCP only sends minimal
> info actually.
>
> ​You might want to look again:
Source IP (aka client IP) is in the IP portion of the headers, source port
is in the TCP part.​

​ If this information was not present, the server would have no way of
sending replies back to the initiator.
​​

> The argument "hey, this is open source, just contribute" only goes that
> far. Open source projects have to have strong authorities who integrate
> patches and drive development.
>
​There are multiple ways an open source project can thrive.​


> In this case security concern isn't addressed for 3 months. In another bug
> report I asked why some obscure error occurs, and also no answer.
>
​The pitfalls of open source.  It does not always go smoothly, though this
is more of a software development problem in general.  ​

> Open source project can not function only driven by contributors.
>
​On the contrary, open source only really matters to the contributors.
There are many ways other than writing code to be a contributor, but
contributors are really the only ones who matter.

Sometimes you have paying customers, though really payment is a form of
contribution.

You might also want to review this essay on asking smart questions,
particularly to developers:
http://www.catb.org/esr/faqs/smart-questions.html

I know I found this essay to be very helpful when I was starting out.

Cheers,

**Comment by yurivict** [comment]
> If this information was not present, the server would have no way of
sending replies back to the initiator.

Source address in TCP is NAT translatable, and is the minimally necessary information to maintain the connection. And OP talks about the passing IP in protocol level which isn't NAT translated, and reveals the client IP. So there is no relevant TCP shortcoming here.

> You might also want to review this essay on asking smart questions, particularly to developers: http://www.catb.org/esr/faqs/smart-questions.html

Trolling is prohibited by GitHub TOS. All I can say. Stay constructive, and on the topic.
This is not a forum to discuss Open Source philosophies, and give reading advice.

**Comment by secur1tyge3k** [comment]
Any updates on this issue?

This issue is a "security" concern.
Sending client information is a VERY BAD thing.
Each packet must be minimum.
Only BLACKHAT HACKERS and SERVER ADMIN will love it, but not okay for clients.

I don't know why @dnobori say nothing about this security problem.
My company is discussing about buying Packetix VPN... I should alert them NOT TO BUY IT and
advise them to buy OpenVPN instead.

Is this how you react to security problem, @dnobori?

---

@Owyn
> At least VPN server can't sniff what sites you visit

No. SEVPN and PXVPN server software *can* sniff the traffic if it is set to "monitor" mode.

@yurivict
> people probably shouldn't use SoftEtherVPN at all.

I totally agree.

---

PATCH SUGGESTION

[CLIENT]
Please stop sending these information to server.
Client version: XXXX,
Client build number: XXXX,
Client OS name: "Windows FUCKYOU",
Client OS version: "Build 1234, Multiprocessor Free, Service FUCK 1 (1234.XXX.XX-XX)",
Client product ID: "--",
Client host name: "YYYYY",
Client IP address: "LOCALIP.123",

[SERVER]
Please stop sending these to client.
Server product name: "SoftEther VPN Server (64 bit)"
Server version: 1234
Server build number: 5678

---

If you never fix this issue for the end of 2015, I'll convince all my relatives to stop using SEVPN/PXVPN.

**Comment by secur1tyge3k** [comment]
Someone, please post this issue to:

softether-vpn-security [at] softether.org

I already tried it, but my corporate server reject it.

**Comment by secur1tyge3k** [comment]
"Dear security experts

If you find a bug or a security vulnerability please kindly inform us about the problem immediately so that we can fix the security problem to protect a lot of users around the world as soon as possible.

Our e-mail address for security reports is: softether-vpn-security [at] softether.org"

https://softether.org/5-download/src

**Comment by secur1tyge3k** [comment]
What kind of problem:
1. Potential Information leakage
2. Attacker will know about client environment by intercept unencrypted/weak SEVPN/PXVPN packet
3. Attacker will know about the network which client connecting to. (e.g., 192.168.X.* range)

Until SE fix this issue:
We can:
1. Stop using SEVPN/PXVPN and go back to OpenVPN.
2. Modify the code to send fake information

**Comment by SuperSpyTX** [comment]
From what I've read, I'm not sure if this sent in plaintext or if it's ciphered.

Is this information sent in plaintext before the session is initialized?

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed
