### ISSUE TITLE
Question for broad member

### ISSUE THREAD

**Issue by zero88** [SoftEtherVPN/SoftEtherVPN#1304]
Hi, there!

Sorry boarding team for removing ticket format, I want to ask some questions, but forum doesn't active to me.

Currently, I intend building IoT solution with a thousand multi-tenant IoT devices(linux armv7) under SoftEtherVPN network.
The server will be deployed on cloud: Google cloud in GCE (in docker) or GKE.
My strategy is opensource in another repository and will provide under Apache License 2.0. So please give me any copyright from current repository that I need to take care in my repository.

For my project status:
- Deploy automatically on device side is almost finished. 
- Right now, I move on next step with VPN server to make VPN manager on web based that adapt with my objective.

I want to know a status of some ticket:
- https://github.com/SoftEtherVPN/SoftEtherVPN/pull/615
- https://github.com/SoftEtherVPN/SoftEtherVPN#built-in-softether-server-vpn-json-rpc-api-suite

Because no actual changelog, then my questions are:
- These tickets/features are available on https://github.com/SoftEtherVPN/SoftEtherVPN_Stable or not? If not, so I need to use release version in https://github.com/SoftEtherVPN/SoftEtherVPN. 
- Any drawbacks if using develop version in production server? 
- Is release tag in develop repository is reliable like 90% that compare to Stable version?
- Any matrix version compatible between vpnserver/vpnclient/vpnbridge? For example: using vpnclient-v4.34-9745-beta on stable repository with vpnserver-v5 on develop repository and otherwise

Thank you so much

**Comment by davidebeatrici** [comment]
Hi,

Nothing was changed in this repository regarding the native protocol, meaning that the stable client should work just fine.

As for reliability, we cannot guarantee to reach the same level as the stable version because of the many extra features.
However, critical bugs are typically fixed in a timely manner as soon as they are reported and I use the software myself everyday.

As for the licenses: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/legal.txt

**Comment by chipitsine** [comment]
can we try https://github.com/SoftEtherVPN/SoftEtherVPN/discussions instead of forum ?

**Comment by zero88** [comment]
ya, lgtm. I will migrate this ticket to discussion
