### ISSUE TITLE
Bad MAC address on creating new virtual NIC

### ISSUE THREAD

**Issue by domosekai** [SoftEtherVPN/SoftEtherVPN#1444]
I have this issue on two Win 10 computers but I can't reproduce it on a Win 10 VM.

When creating a virtual adapter in the client manager, its MAC address always shows "00-00-01-00-00-01". If I then create a second adapter, the second one has a normal MAC (5E-). But if I delete the first one and recreate (leave the second one unchanged), the new adapter again has 00-00-01-00-00-01 MAC. 

Creating via vpncmd has the same issue.

This issue does not arise with old drivers. Tested in 9674.

Also, the Interface Metric of the 00-00-01-00-00-01 adapter is not set to 1 in the registry.

**Comment by domosekai** [comment]
![image](https://user-images.githubusercontent.com/54519668/127620716-c133d84c-e863-4ef2-a7db-87a61c510e56.png)

**Comment by davidebeatrici** [comment]
Probably caused by #1295, I'm not sure why though.

For reference:

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/101d79d7c3c5d978a82545b1c2b94bbd480285a6/src/vpndrvinst/Device.c#L278-L283

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/101d79d7c3c5d978a82545b1c2b94bbd480285a6/src/vpndrvinst/Device.c#L478-L484
