### ISSUE TITLE
Debugging vpnserver

### ISSUE THREAD

**Issue by alolis** [SoftEtherVPN/SoftEtherVPN#145]
Hello,

I am having trouble debugging SoftEtherVPN since it seems that the following is happening in `main`

````c
// WinMain function
int main(int argc, char *argv[])
{
	VgUseStaticLink();

#ifdef	OS_WIN32

	return MsService(GC_SVC_NAME_VPNSERVER, StartProcess, StopProcess, ICO_CASCADE, argv[0]);
#else	// OS_WIN32
	return UnixService(argc, argv, "vpnserver", StartProcess, StopProcess);
#endif	// OS_WIN32
}
````

A "UnixService" is returned and then application exists (but vpnserver process continues to exist). Is there a recommended way to debug the vpnserver? Even if I have to copy-paste some code in main, I do not mind

Cheers

**Comment by moatazelmasry2** [comment]
Why did you close this issue? How did you solve the problem?
I'm also trying to debug softether. And I found out the reason why it is exiting is because there was another softether process running in the background. When I killed it, the program didn't exit.

My problem is a bit different, while starting, any breakpoint is used successfully, but after starting, eclipse seem to ignore all the breakpoints. Did you have a similar situation??

**Comment by alolis** [comment]
@moatazelmasry2, I am starting the compiled vpnserver and then I [attach](http://stackoverflow.com/questions/655853/is-it-possible-to-attach-a-debugging-session-to-a-running-program-in-eclipse-cdt) the Eclipse CDT debugger the process.

**Comment by MtCedarNet** [comment]
Did you try execsvc option?
vpnserver execsvc

**Comment by moatazelmasry2** [comment]
@alolis  Thanks. This solved my problem. Any ideas why you can't start a debugger directly from eclipse?

**Comment by moatazelmasry2** [comment]
@MtCedarNet Yes I'm starting with execsvc

**Comment by alolis** [comment]
@moatazelmasry2 I can't remember exactly, it's been some time now.
