### ISSUE TITLE
Can't find LS_LISTENER_DOS related code

### ISSUE THREAD

**Issue by ovear** [SoftEtherVPN/SoftEtherVPN#1541]
Hi,
Recently i found my softether server's log cotains some "dos attack" logs. After reading & searching source code from [SoftEtherVPN/SoftEtherVPN_Stable](https://github.com/SoftEtherVPN/SoftEtherVPN_Stable), I can find nothting about this error.
I try to use "LS_LISTENER_DOS" as keyword to search, nothing found. The TCPAcceptedThread function from `Listener.c` also not include this logic.
Is there anything i missed?

Thanks

**Comment by ovear** [comment]
Hi,
After compile softethet vpn server on my own, i notice that this function won't work in custom build version, and this action is fit to the source code. Besides that there are other difference between official and open-source version, eg: vpngate won't work in customize open source version.
I am wondering why this happened, is there any else difference  between official and open source verison? I can understand vpngate is a private service that won't open source. But dos protection ability is a basic function, which would be great for vpn server and seems shouldn't be close source.

Look forward to your reply.

**Comment by dnobori** [comment]
Hello.

SoftEther VPN Server Stable Edition is sold as PacketiX VPN Server in the Japanese market, and this is the source of funding for the development of SoftEther VPN Server Stable Edition. When SoftEther Corporation receives a question from a paid customer of SoftEther VPN Server, SoftEther Corporation is responsible for explaining what is the difference from the free version of SoftEther VPN Server. If PacketiX VPN Server does not sell well in the Japanese market, everyone will not be able to use SoftEther VPN Server Stable Edition because we cannot continue to develop and release it freely to worldwide. Therefore, the sales of PacketiX VPN Server in the Japanese market will benefit the users of SoftEther VPN Server all over the world.
In order to sell PacketiX VPN Server in the Japanese market, SoftEther VPN Server Stable Edition has some functional limitations when it is running on a Japanese IP address. These functional limitations include RADIUS authentication function and DoS attack prevention function.
The binary version of SoftEther VPN Server Stable Edition actually includes the implementation of the above security features. And these work only when the IP address is outside Japan. They do not work with Japanese IP address. It is a regional lock system. The source code version of SoftEther VPN Server Stable Edition has the anti-DDoS attack feature removed. This is because if this feature is included in the source code, any user in the Japanese market can unlock it.
You can find the above information on the SoftEther VPN web page in Japanese: https://ja.softether.org/3-spec/cureent_limitations
