### ISSUE TITLE
Server Softether crash few minute ago after client connection

### ISSUE THREAD

**Issue by 19Lopez19** [SoftEtherVPN/SoftEtherVPN#1554]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
**Architecture:** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

[Description of the bug]

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [And so on...]
[vpn_20220219.log](https://github.com/SoftEtherVPN/SoftEtherVPN/files/8102126/vpn_20220219.log)
[vpn_20220219.zip](https://github.com/SoftEtherVPN/SoftEtherVPN/files/8102131/vpn_20220219.zip)

**Comment by andrewfer000** [comment]
Thanks for providing your logs. But can I have some more details?

What was the server Version, OS, and Hardware?

What was the Client Device? What protocol was it trying to use?

Are you using standard or RADIUS/NT Authentication?

Did you build SE from source or did you use a binary? If using SoftEther VPN Client, did you compile that from source or use a pre-built binary?  

The more detial, the better.

**Comment by 19Lopez19** [comment]
Hello andrew, thank's for your answer.
Server's SO is a Windows server 2012 R2 hardware intel (i5 processor, 64 Gb RAM). Softether server 4.38 Build 9760 rtm. Client 4.38 Build 9760 rtm. I'm using standard Authentication

**Comment by andrewfer000** [comment]
@19Lopez19, This GitHub is for SoftEther Developer Edition (5.x+). SoftEther 4.x is nearly a completely different product compared to this one due to it's age and different development model. For 4.x related issues, please post to the https://www.vpnusers.com/ Forum and ask for help there since the people on the forum are using the 4.x version. 

What I suggest is obtaining the latest developer edition from our Azure Pipelines. Here is a direct download for the Server and Client installer exe files. [(Download)]( https://dev.azure.com/SoftEther-VPN/004d90d2-bc6f-49f8-8eae-e9e67e0d808b/_apis/build/builds/778/artifacts?artifactName=Installers&api-version=7.0&%24format=zip) It works nearly the same as 4.x and you should be able to use your 4.x configuration file. However, the 4.x GUI Management tools will have issues with this version and I suggest you use the `vpncmd` command line tool.

**Comment by domosekai** [comment]
No response. Closing.
