### ISSUE TITLE
how can I ensure people who resign can not connect into ? how to implement scanning code to log in？

### ISSUE THREAD

**Issue by marklinglon** [SoftEtherVPN/SoftEtherVPN#1614]
Hi, there!
two questions
how can I ensure people who resign can not connect into ? how to implement scanning code to log in？

**Comment by r4j4h** [comment]
Because users must use auth, remove their access via your auth mechanism.

This could be done by deleting their User via Admin controls, or via your RADIUS mechanism, etc. If you used certificates and their certificates is used elsewhere then you will need to remove them there, or investigate Certificate Revocation Lists or other mechanisms that you might have in play that work in that space, otherwise you will need to sign new certs and distribute them to be sure.

Scanning code reading the log files would probably be the easiest route

**Comment by r4j4h** [comment]
Looks like I forgot that SoftEther's certificate management facilities also have a Certificate Revocation List functionality that could possibly be of use
