### ISSUE TITLE
Need new feature 'android and iOS use 'softether VPN' protocol'

### ISSUE THREAD

**Issue by DrHomer** [SoftEtherVPN/SoftEtherVPN#1624]
Hi, there!

I need new feature. 
For android and iOS use 'softether VPN' protocol. Is it possible?  Next figure show absent this feature: 
![](http://www.softether.org/@api/deki/files/410/=SoftEtherVPN_Page_03.jpg)

If it's impossible can you explain why?

**Comment by davidebeatrici** [comment]
And don't forget about WireGuard, if you use the version from this repository.

**Comment by lixh1223** [comment]
CentOS7版视频安装教程：https://youtu.be/fWGw6Qdh1pY
Windows版视频安装教程：https://youtu.be/lXb7FxxEcE0

**Comment by domosekai** [comment]
Duplicate issue of #1019 #453 #1105 #545

**Comment by heygo1345678** [comment]
> And don't forget about WireGuard, if you use the version from this reposi

> Duplicate issue of #1019 #453 #1105 #545



> And don't forget about WireGuard, if you use the version from this repository.

I have test openvpn ,open sstp client on android platform. there are no issues about thest two apps.I also tested  Softether 
 windows client  and Linux bridge,due to the tap support, i can use ipv6 network .but openvpn android and  open sstp client no ipv6 network inside the tunnel.
 
Does the new wireguard support ipv6 nat inside the tunnel?
