### ISSUE TITLE
Admin IP & Port Suggestion

### ISSUE THREAD

**Issue by adminport** [SoftEtherVPN/SoftEtherVPN#173]
Suggestions:
1. Enabling use of partial wildcards, e.g. 192.168.1.*
2. Enable the configuration of ports
   A. Use for both VPN & management
   B. Use only for VPN
   C. Use only for management

Thanks.

adminport@grr.la
http://www.vpnusers.com/viewtopic.php?f=7&t=4760

**Comment by adminport** [comment]
Hi anyone?

**Comment by adminport** [comment]
Does this suggestion has any merits?

**Comment by adminport** [comment]
Hi Mr. Daiyuu Nobori please comment.

**Comment by adminport** [comment]
The reason I suggest this is that, if the admin port is opened to the wide (WAN), which is mandatory in SoftEther's current configuration, it's easy for outsiders to bruteforce.

**Comment by adminport** [comment]
Hello......

**Comment by adminport** [comment]
Hello..........

**Comment by adminport** [comment]
Hello.............

**Comment by adminport** [comment]
Hello...................

**Comment by netomx** [comment]
You could help and write it yourself, pal.

**Comment by adminport** [comment]
Sorry for nagging.

**Comment by adminport** [comment]
But I'm still nagging......

**Comment by meganerd** [comment]
Nagging is not how open source works.

Based on your description you have two (well three paths, the third is
useless in my opinion).

First, create a patch for the feature that you want.  Submit the patch for
inclusion into the project so that others may benefit. If you are unable to
create this patch, if it is important enough you could hire someone to do
this for you.  Please be careful with the contract since that contract may
prevent you from contributing that patch to the project.

Second, work around the shortcoming, in this case I accomplish the same
goals as you with firewall rules.

The third option is keep doing what you are doing, which seems silly to me.

Hope this helps,

**Comment by adminport** [comment]
I think this is a valid proposal, and shouldn't take too much work.

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by moatazelmasry2** [comment]
For first suggestion. Yes it is valid. 

For second suggestion, you can indeed achieve that by using firewall rules

**Comment by domosekai** [comment]
Close due to inactivity
