### ISSUE TITLE
Can't establish L2TP connection from server if server has enabled option L2TP

### ISSUE THREAD

**Issue by UkrZilla** [SoftEtherVPN/SoftEtherVPN#270]
Hi guys,

If SoftEther server has enabled L2TP server option then I can't connect from this server to any remote L2TP server
Could you please fix it?
OS: Windows 7/8.1

Thanks

**Comment by MtCedarNet** [comment]
L2TP server and client use same UDP port.
You can't run these at same time on one PC.

**Comment by UkrZilla** [comment]
If I correctly understand only Windows built-in L2TP client use the same port as server?
Does SoftEther support work with L2TP client that use another port?

**Comment by MtCedarNet** [comment]
If SoftEther VPN Server can use another port for L2TP service, how do you change the port which the client access to? 
I have not heard about such client which can change destination port.

**Comment by UkrZilla** [comment]
I mean if client can listen another local UDP port, not 1701. Because server and client have port conflict in case they both are trying to listen the same port.

**Comment by moatazelmasry2** [comment]
@UkrZilla SoftEther should now allow changing the L2TP port 1701 because this is the official port mentioned in RFC 2661:
https://tools.ietf.org/html/rfc2661

You are not supposed to use a VPN Server and client on the same machine. If you are doing this for test purposes only, then please use vagrant or docker
