### ISSUE TITLE
Enterprise-wide acceptance

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#274]
Hello There! I have been working with this amazing tool for at least two years and I notice that it lacks some important enterprise-wide features. When of the issues that one of my friends faced when he was working on creating VPN networks using Softether, is creating lots of virtual hubs at once. for instance, creating 500 VHs with one command or one window for who works on Windows env. I remember he had to create 500 VHs one by one, and for each one he also had to create users for each VH one by onve as well, and for setting some settings also he had to do it one by one. Now, ponder for moments to know what time that job took!. I know, SE enables us to interact with it via command line and then we can use some scripts to create whatever we would like to do **"BUT"** not everyone knows how to script or to use scripting languages to finish their jobs. I assume that you know about Cisco IOS, and as you might know you can create VLANS, SVI, and set their settings for all or for specific groups of them with one command, that is exactly what I am talking about. I really believe that adding this feature will push Softether further to enterprise world. Let me know your thoughts about this.

Thanks '__ ,'

**Comment by moatazelmasry2** [comment]
@ghost . This could turn out to be a great feature, but please help me understand how this should be implemented. I'm not really aware of Cisco IOS. 

But to my understanding if you want to get a redundant job done, like creating 500 hubs or adding thousands of users, then a script of some kind should be used. What you are describing here is a bit of quite wide use case. So how can we narrow (generalize) that a bit so that it is useful to the community????
