### ISSUE TITLE
Data compression of OpenVpn in SoftEtherVpn

### ISSUE THREAD

**Issue by hpsisme** [SoftEtherVPN/SoftEtherVPN#297]
Can you add this feature?

**Comment by chipitsine** [comment]
compression is deprecated, have a look

https://docs.openvpn.net/phasing-out-compression-due-to-voracle-vulnerability/

**Comment by subsys-R9boq8** [comment]
Is the similar attack probable on Softether VPN's traffic compression function? Because the VORACLE attack seems very similar to general case SSL chosen plaintext attack like [CRIME](https://en.wikipedia.org/wiki/CRIME) and [BREACH](https://en.wikipedia.org/wiki/BREACH_%28security_exploit%29). I don't mean to disturb, but this is kind of worrying to me.
