### ISSUE TITLE
Naming and code convention?

### ISSUE THREAD

**Issue by GildedHonour** [SoftEtherVPN/SoftEtherVPN#359]
1) Do we have a common naming and code convention in the project?

2) There're many tab spaces in the project, I propose to replace all them with whitespaces.

**Comment by dnobori** [comment]
1. My favorite naming convention is like Windows Kernel source code's. I believe that most of the existing codes of SoftEther VPN is using the similar convention. I suppose it is called Pascal. (I do not families with the code convention.)

2. Could you please let me know the reason why we should avoid tab spaces?

**Comment by GildedHonour** [comment]
2. for instance, this https://www.quora.com/Why-would-a-coder-use-spaces-over-tabs

**Comment by chipitsine** [comment]
Usually, people cannot agree on tabs or spaces

Maybe, separate forks for tabs and spaces? Otherwise, it will never end

**Comment by macvk** [comment]
The next thing will be moving from C++ to Python, I guess. 

Mr Nobori must say 1. and 2. is a rules but not something for discussion.

**Comment by dnobori** [comment]
I understool the reason about recommending spaces rather than tabs. I agree to reform them with spaces.

**Comment by dnobori** [comment]
For the common naming and code convention, I agree to change it as necessary based on the entire consensus of contributors. It is a good thing that using good convention which programmers want to use.

**Comment by moatazelmasry2** [comment]
I'm against spaces and I'm aware of the drawbacks. 
But specifically for this project I'm against converting tabs to spaces or vice versa etc.. because this will also mess the blame log and will touch almost every line in the code.

If there are concerns about different tab settings in the editor, here's a suggestion we use in our company:
1- Write down a developers coding guide, specifying exactly everything: brackets, spaces in conditions, new lines, etc..
2- Offer code formatters for popular IDE's: Visual Studio, eclipse etc.. and let people download and configure them for SE developement. WDYT??

**Comment by davidebeatrici** [comment]
We decided to keep using tabs, for the reasons mentioned by @moatazelmasry2 and for personal preference.

However, that's only for indentation. For perfect alignment spaces are often required.

As for the naming convention: Pascal case (each word capitalized) for functions, snake case for variables.
