### ISSUE TITLE
High IO traffic

### ISSUE THREAD

**Issue by cdcseacave** [SoftEtherVPN/SoftEtherVPN#361]
Thank you for such a great and useful software. I recently installed it and the process was as  easy as can be.

I noticed however a very usual high IO traffic on the client side. When connected to a server, the IO reads are on average around 35MB/s with spikes of 300MB/s for several seconds, and the IO writes around the half of the reads. In only 3 minutes the total IO traffic is around 60GB and 25GB respectively. The network traffic seems reasonable though. I am using it on Windows 10 x64 16299.

What can be the explanation?

**Comment by dnobori** [comment]
That is the total amount of exchanged buffer size between user-mode service and kernel-mode virtual network adapter using Read/Write API. Please read the source code of the Neo device driver to see the cause. The fundamental cause is that the adapter does not report the exact byte size of exchanged data. It reports just the total buffer size and become false report. Since the driver is using buffered I/O, it does not affect any performance. You can simply ignore it.
