### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by canusuck** [SoftEtherVPN/SoftEtherVPN#416]
1. How many people can simultaneously connect using the L2TP / IPsec protocol?
2. How to get rid of DNSLeaks? For example, I have a server in Sweden, how can I receive only DNS Sweden?
3. How to connect correctly to Linux?
4. Is ikev2 safer than l2tp? Is it faster? How much can it be used at the same time?

Thank you in advance for your response.

**Comment by macvk** [comment]
SE doesn't support IKEv2, I think.

**Comment by moatazelmasry2** [comment]
1. AFAIK there are no hard coded limits. You are only bound by your hardware capabilities
2. What do you mean "how can I receive only DNS Sweden" ??
3. How to connect correctly to Linux?? Question is not clear. What is the problem exactly. Are you aware of the project's documentation?
4. ikev2 is not implemented. l2tp on SoftEther is quite safe since it is using ikev1(ipsec) transport mode for encryption.

**Comment by moatazelmasry2** [comment]
If these answers cover your question, I'd like to close this issue within the next few days
