### ISSUE TITLE
The IP doesn't change on Linux 

### ISSUE THREAD

**Issue by Khsed4** [SoftEtherVPN/SoftEtherVPN#431]
Hi, I hope u all do well. I am using SoftEther VPN client on my private and own server, on  both  window and Linux, as u know windows has a GUI and it's easy to connect to my own server with it , but the problem is raised while I am using Linux, on Linux as the server logs shows it connects at first but after a few seconds it's disconnect and terminates the connection however on windows there is no problem for connecting using the same username and password .Here is the server log :
**Client OS name: "Linux", Client OS version: "Unknown Linux Version", Client product ID: "--", Client host name: "khaleq-VirtualBox", Client IP address: "10.0.2.15", Client port number: 34278, Server host name: "139.59.68.11", Server IP address: "139.59.68.11", Server port number: 443, Proxy host name: "", Proxy IP address: "0.0.0.0", Proxy port number: 0, Virtual Hub name: "vpn", Client unique ID: "2BA44D5C538C8863B6A1B9B262F6F26C")
2018-01-22 05:29:39.037 On the TCP Listener (Port 443), a Client (IP address 103.53.26.2, Host name "103.53.26.2", Port number 60595) has connected.
2018-01-22 05:29:39.037 For the client (IP address: 103.53.26.2, host name: "103.53.26.2", port number: 60595), connection "CID-68" has been created.
2018-01-22 05:29:39.413 SSL communication for connection "CID-68" has been started. The encryption algorithm name is "RC4-MD5".
2018-01-22 05:29:42.175 Connection "CID-68" has been terminated.**
something that  is amazing for me is after the first time it's connected to the server it's always saying connected  however server logs shows that the connection is terminated .as the screenshots show 
![capture](https://user-images.githubusercontent.com/33887898/35208142-592df216-ff64-11e7-83f5-a3fa6553271c.PNG)

and the next problem is it **never changes the IP address and the location when using Linux, however, it says it's connected to the server while as I said before it actually changes the IP and location when I use SoftEther VPN client manager on windows**.

**Comment by olih10200** [comment]
maybe, not the "relevant" solution, but try to listen the connection (via monit or whatever), and use dhclient command to renew the ip ... (or use static ips within vpn - i prefer it for posix-based systems only, because them run any kind of services: like dns[bind9] local ftp/ssh/etcetera)

**Comment by Khsed4** [comment]
@olih10200  really appreciate your response, but still, it is the same problem, it shows connected but it never changes the IP and server logs terminate the connection after few seconds.

**Comment by Khsed4** [comment]
@moatazelmasry2 can u please response to this question

**Comment by Nemesiz** [comment]
SoftEther client on Linux do nothing to routing table or interface IP. You have to set manually or configure it for static or dhcp network interface.

auto tap_hub1
iface tap_hub1 inet static
	address 192.168.30.2
	netmask 255.255.255.0

auto tap_hub2
iface tap_hub2 inet dhcp

**Comment by top-master** [comment]
I think that did not explain clearly enough what is the working setup.
we modify the Softether VPN local bridge to use a TAP device instead of the real NIC (here it is eth0 on my server).
Then, under Linux, I modified the network settings for the system by using a Linux bridge linking eth0 to the new TAP device in order for both devices to see the external world.

I provide here the content of /etc/network/interfaces on my server (the settings are the same on the other server at the opposite side of the VPN link):
-------------------------------------------------------------------------
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet static
address 0.0.0.0

# The VPN TAP network interface
auto tap_vpn
iface tap_vpn inet static
pre-up tunctl -t tap_vpn
address 0.0.0.0
hwaddress ether XX:XX:XX:XX:XX:XX

# The bridge network interface
auto br0
iface br0 inet static
bridge_ports eth0 tap_vpn
address 192.168.1.1
netmask 255.255.255.0
network 192.168.1.0
broadcast 192.168.1.255
gateway 192.168.1.120
-------------------------------------------------------------------------
For the TAP MAC address, use eth0's MAC address as the bridge will use either eth0's one or the TAP's one depending on which comes up last during the bridge creation. So using eth0's MAC address for the TAP device ensure that the bridge will use a real MAC address for communications with the outside...

The TAP device is created by Linux instead of softether VPN in order for it to be included in the Linux bridge at boot time as network interfaces are supposed to be up before any VPN can be created.
The trick is to ensure that the TAP device in Linux has the "tap_" prefix prepended to the TAP device name used in softether VPN (and also the same MAC address).

Here is an extract of Softether VPN configuration file for the corresponding local bridge:
-------------------------------------------------------------------------
declare LocalBridgeList
{
bool DoNotDisableOffloading false

declare LocalBridge0
{
string DeviceName vpn
string HubName BRIDGE
bool LimitBroadcast false
bool MonitorMode false
bool NoPromiscuousMode false
string TapMacAddress XX-XX-XX-XX-XX-XX
bool TapMode true
}
}
-------------------------------------------------------------------------

I hope I have been a little clearer with the settings of the servers... but I did never used the client which's setting can be different

**Comment by Nemesiz** [comment]
SoftEther works great with creating tap device and debian/ubuntu network interface config works too. Try this:
```
auto lo
iface lo inet loopback

allow-br0 eth0
iface eth0 inet manual

allow-br0 tap_vpn
iface tap_vpn inet manual
    up brctl addif br0 $IFACE
    pre-down brctl delif br0 $IFACE

auto br0
iface br0 inet static
    bridge_ports eth0
    address 192.168.1.1
    netmask 255.255.255.0
    network 192.168.1.0
    broadcast 192.168.1.255
    gateway 192.168.1.120
```

**Comment by Nemesiz** [comment]
If you will use openvswitch:
```
allow-vmbr0 eth0
iface eth0 inet manual
	ovs_type OVSPort
	ovs_bridge vmbr0

auto vmbr0
iface vmbr0 inet static
	address 10.10.8.1
	netmask 255.255.248.0
	ovs_type OVSBridge
	ovs_ports eth0
```

**Comment by top-master** [comment]
that means a TAP device alone is not enough and you need to change the **/etc/network/interfaces** file

**Comment by Nemesiz** [comment]
I set up /etc/network/interfaces to automatically do something with SoftEther device on creating/destroying.
I guess creating TAP with tunctl may cause SoftEther error on creating TAP device because it already exist.

**Comment by DragoonX6** [comment]
@Khsed4 I don't know if this is still relevant for you, but on Linux you will have to setup routing manually sadly.

What you want to do after connecting is run a DHCP client on the VPN link, and provide a static route to the VPN server.

An example using iptools2 and dhcpcd:
* Connect to the VPN.
`vpncmd localhost -client -cmd AccountConnect YourAccount`

* Request IPs from the DHCP server running on the VPN server.
I'm assuming your adapter is called vpn_sevpn.
Setting the metric to 1 makes sure the routes are inserted before your current routes.
`sudo dhcpcd --metric 1 -n vpn_sevpn`

* Finally add a static route to the VPN server over your actual physical LAN.
Let's assume 8.8.8.8 is the IP of your server, and that 192.168.0.1 is your local gateway
`sudo ip route add 8.8.8.8 via 192.168.0.1`
If your IP address overlaps with what you get from the VPN's DHCP server, make sure you add the device by adding "dev eth0" add the end of your command
`sudo ip route add 8.8.8.8 via 192.168.0.1 dev eth0`

**Comment by sagar-chandarana** [comment]
dup https://github.com/SoftEtherVPN/SoftEtherVPN/issues/431
