### ISSUE TITLE
Server 9667 cannot make in redhat

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#548]
Version: 9667 (from http://www.softether-download.com/en.aspx?product=softether)
VPN Server, Linux, Intel x64
Server: CentOS Linux release 7.5.1804 (Core)
Linux version: 4.16.11-1.el7.elrepo.x86_64

cc -Q -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)

make error:
make[1]: Entering directory `/root/vpnserver'
Preparing SoftEther VPN Server...
ranlib lib/libcharset.a
ranlib lib/libcrypto.a
ranlib lib/libedit.a
ranlib lib/libiconv.a
ranlib lib/libintelaes.a
ranlib lib/libncurses.a
ranlib lib/libssl.a
ranlib lib/libz.a
ranlib code/vpnserver.a
gcc code/vpnserver.a -O2 -no-pie -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpnserver
gcc: error: unrecognized command line option ‘-no-pie’
make[1]: *** [i_read_and_agree_the_license_agreement] Error 1
make[1]: Leaving directory `/root/vpnserver'

Any ideas?

Thanks a lot.

**Comment by moatazelmasry2** [comment]
Could you please try compiling again using the instructions in:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/BUILD_UNIX.md
And compile from the master branch of this repo

**Comment by scegg** [comment]
Failed in ./configure
CMake 3.0 or higher is required.  You are running version 2.8.12.2

**Comment by chipitsine** [comment]
gcc-4.8 seems to be too old to understand ``-no-pie```

wait a bit ? I'll provide a patch and a solution how to compile (if you are in hurry, use SCL, which provides modern gcc compiler for redhat)

**Comment by scegg** [comment]
hmm, i'm not hurry for updating.
Just mention that the released compiled version cannot work on CentOS 7.5

**Comment by chipitsine** [comment]
```
yum install -y epel-release
yum install -y centos-release-scl-rh
yum install -y devtoolset-4-gcc cmake3
scl enable devtoolset-4 bash
cmake3 .
make
```

please provide a feedback, so can update build instructions


how did you install compiled version? can you provide step by step ?

**Comment by scegg** [comment]
Haven’t test your yum code yet. Signed off today and will test it tomorrow.

Install compiled version:
Download it from official site, tar it, make

**Comment by chipitsine** [comment]
do you mean "build from source" ? or did you download binary package?

**Comment by scegg** [comment]
Binary. As I mentioned in line 1 lol

**Comment by chipitsine** [comment]
I managed to build on centos 7.5 using just cmake3 (with default gcc-4.8)

**Comment by chipitsine** [comment]
I managed to reproduce your error message.

**Comment by scegg** [comment]
cmake3 works well. (in building from source code)

Thanks a lot.

I'll close this issue now. But I still suggest you to fix the released binary file.

**Comment by scegg** [comment]
Any code changed since last few hours?
When I try to repo this step in a new server, in cmake3 procedure, now the error is:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIB_CRYPTO
    linked by target "mayaqua" in directory /root/SoftEtherVPN/src
LIB_NCURSES
    linked by target "mayaqua" in directory /root/SoftEtherVPN/src
LIB_READLINE
    linked by target "mayaqua" in directory /root/SoftEtherVPN/src
LIB_SSL
    linked by target "mayaqua" in directory /root/SoftEtherVPN/src
LIB_Z
    linked by target "mayaqua" in directory /root/SoftEtherVPN/src

-- Configuring incomplete, errors occurred!

**Comment by moatazelmasry2** [comment]
Has the new error been resolved?

**Comment by scegg** [comment]
@moatazelmasry2 
Workaround is working. Binary file released still cannot support CentOS 7.5 by default.

**Comment by chipitsine** [comment]
binary file seem was released from https://github.com/SoftEtherVPN/SoftEtherVPN_Stable
@moatazelmasry2 - any idea where to report such issues ?

**Comment by moatazelmasry2** [comment]
Yes and no. This repo is the original SoftEther. @Daiyuu created a fork
"stable" and is uploading binaries to his softether.org website. We have
really no saying in what goes into the stable repo or the download website.

My suggestion would be to stick to this repo, and talk Daiyuu into making
this Repo the official place to download binaries

**Comment by chipitsine** [comment]
"this" repo is 5.x
I seen 4.X in error report, right ? Also, I downloaded from softether.org, followed build instructions, and there 4.X

**Comment by moatazelmasry2** [comment]
I understand what you are saying. Still the fact remains is we have no influence on what is going into the stable repo or what is being uploaded to softether.org. And that's why I'm always asking people to first compile from this Repo as this is something we can actually fix. 

In the stable Repo you can not create an issue and vpnusers.com is like  black hole. So no idea where to report such issues

**Comment by dnobori** [comment]
Thank you reporting this problem.
I fixed this on the Stable Build (SoftEther VPN 4.27 Build 9668 Beta).

**Comment by zxc159789** [comment]
**I made an error while compiling at 4.28 9669  How should I solve this problem?**
**What is the role of the -no-pie parameter**

gcc -no-pie code/vpnserver.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpnserver || gcc code/vpnserver.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpnserver
gcc: error: unrecognized command line option ‘-no-pie’
ranlib code/vpncmd.a
gcc -no-pie code/vpncmd.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpncmd || gcc code/vpncmd.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpncmd
gcc: error: unrecognized command line option ‘-no-pie’


**After that I tried 4.27 9668
Compile successfully but no ./install.sh file**

gcc code/vpnserver.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpnserver || gcc -no-pie code/vpnserver.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpnserver
ranlib code/vpncmd.a
gcc code/vpncmd.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpncmd || gcc -no-pie code/vpncmd.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpncmd
./vpncmd /tool /cmd:Check
vpncmd command - SoftEther VPN Command Line Management Utility
SoftEther VPN Command Line Management Utility (vpncmd command)
Version 4.27 Build 9668   (English)
Compiled 2018/05/29 21:51:20 by yagi at pc33
Copyright (c) SoftEther VPN Project. All Rights Reserved.

[root@localhost vpnserver]# ls -al
total 10476
drwxrwxrwx  5 root root     334 Sep 29 08:00 .
drwx------ 19 jiel jiel    4096 Sep 29 08:00 ..
-rwxrwxrwx  1 root root    2955 May 29 21:13 Authors.txt
drwx------  2 root root       6 Sep 29 08:00 chain_certs
drwxrwxrwx  2 root root      41 Sep 29 08:00 code
-rwxrwxrwx  1 root root 1296620 May 29 21:13 hamcore.se2
-rwxrwxrwx  1 root root    1533 May 29 21:13 .install.sh
-rw-------  1 root root     867 Sep 29 08:00 lang.config
drwxrwxrwx  2 root root     170 Sep 29 08:00 lib
-rwxrwxrwx  1 root root    3010 May 29 21:13 Makefile
-rwxrwxrwx  1 root root   30801 May 29 21:13 ReadMeFirst_Important_Notices_cn.txt
-rwxrwxrwx  1 root root   36296 May 29 21:13 ReadMeFirst_Important_Notices_en.txt
-rwxrwxrwx  1 root root   50695 May 29 21:13 ReadMeFirst_Important_Notices_ja.txt
-rwxrwxrwx  1 root root   58902 May 29 21:13 ReadMeFirst_License.txt
-rwxr-xr-x  1 root root 4611800 Sep 29 08:00 vpncmd
-rwxr-xr-x  1 root root 4611880 Sep 29 08:00 vpnserver


**My system is**
[root@localhost vpnserver]# lsb_release -a
bash: lsb_release: command not found...
[root@localhost vpnserver]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core) 
[root@localhost vpnserver]#  cat /proc/version
Linux version 3.10.0-862.11.6.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Tue Aug 14 21:49:04 UTC 2018
[root@localhost vpnserver]# make -v
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[root@localhost vpnserver]# cmake -version
cmake version 2.8.12.2

**Comment by dnobori** [comment]
Could you please paste the *full results* of the `make` command?

**Comment by dnobori** [comment]
If the message
```
The command completed successfully.
--------------------------------------------------------------------
The preparation of SoftEther VPN Server is completed !
```
is displayed after the make command, it is no problem.

**Comment by zxc159789** [comment]
> If the message
> 
> ```
> The command completed successfully.
> --------------------------------------------------------------------
> The preparation of SoftEther VPN Server is completed !
> ```
> is displayed after the make command, it is no problem.


hello 
Bold display is wrong
And did not generate the install.sh file


make[1]: Entering directory `/root/vpnserver'
Preparing SoftEther VPN Server...
ranlib lib/libcharset.a
ranlib lib/libcrypto.a
ranlib lib/libedit.a
ranlib lib/libiconv.a
ranlib lib/libintelaes.a
ranlib lib/libncurses.a
1ranlib lib/libssl.a
ranlib lib/libz.a
ranlib code/vpnserver.a
gcc -no-pie code/vpnserver.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpnserver || gcc code/vpnserver.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpnserver
**gcc: error: unrecognized command line option ‘-no-pie’**
ranlib code/vpncmd.a
gcc -no-pie code/vpncmd.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpncmd || gcc code/vpncmd.a -O2 -fsigned-char -pthread -m64 -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a lib/libintelaes.a -o vpncmd
**gcc: error: unrecognized command line option ‘-no-pie’**
./vpncmd /tool /cmd:Check
vpncmd command - SoftEther VPN Command Line Management Utility
SoftEther VPN Command Line Management Utility (vpncmd command)
Version 4.28 Build 9669   (English)
Compiled 2018/09/11 12:23:27 by yagi at pc33
Copyright (c) SoftEther VPN Project. All Rights Reserved.

VPN Tools has been launched. By inputting HELP, you can view a list of the commands that can be used.

VPN Tools>Check
Check command - Check whether SoftEther VPN Operation is Possible
---------------------------------------------------
SoftEther VPN Operation Environment Check Tool

Copyright (c) SoftEther VPN Project.
All Rights Reserved.

If this operation environment check tool is run on a system and that system passes, it is most likely that SoftEther VPN software can operate on that system. This check may take a while. Please wait...

Checking 'Kernel System'... 
              Pass
Checking 'Memory Operation System'... 
              Pass
Checking 'ANSI / Unicode string processing system'... 
              Pass
Checking 'File system'... 
              Pass
Checking 'Thread processing system'... 
              Pass
Checking 'Network system'... 
              Pass

All checks passed. It is most likely that SoftEther VPN Server / Bridge can operate normally on this system.

The command completed successfully.


--------------------------------------------------------------------
The preparation of SoftEther VPN Server is completed !


*** How to switch the display language of the SoftEther VPN Server Service ***
SoftEther VPN Server supports the following languages:
  - Japanese
  - English
  - Simplified Chinese

You can choose your prefered language of SoftEther VPN Server at any time.
To switch the current language, open and edit the 'lang.config' file.


*** How to start the SoftEther VPN Server Service ***

Please execute './vpnserver start' to run the SoftEther VPN Server Background Service.
And please execute './vpncmd' to run the SoftEther VPN Command-Line Utility to configure SoftEther VPN Server.

Of course, you can use the VPN Server Manager GUI Application for Windows / Mac OS X on the other Windows / Mac OS X computers in order to configure the SoftEther VPN Server remotely.


*** For Windows users ***
You can download the SoftEther VPN Server Manager for Windows
from the http://www.softether-download.com/ web site.
This manager application helps you to completely and easily manage the VPN server services running in remote hosts.


*** For Mac OS X users ***
In April 2016 we released the SoftEther VPN Server Manager for Mac OS X.
You can download it from the http://www.softether-download.com/ web site.
VPN Server Manager for Mac OS X works perfectly as same as the traditional Windows versions. It helps you to completely and easily manage the VPN server services running in remote hosts.

--------------------------------------------------------------------

make[1]: Leaving directory `/root/vpnserver'
[root@localhost vpnserver]# ./install.sh
-bash: ./install.sh: No such file or directory
[root@localhost vpnserver]#

**Comment by davidebeatrici** [comment]
The command is `make install`, not `./install.sh`.

**Comment by dnobori** [comment]
If `make` generates `./vpnserver`, it is ok.

**Comment by zxc159789** [comment]
Yes, I have been able to use it, thank you very much.
Apologize for my carelessness...

manual document  7.3.5 Creating an Executable File Example format is not the same

[root@machine vpnserver]# make
./.install.sh
-------------------------------------------------

It is best to fix it

**Comment by davidebeatrici** [comment]
No worries, thank you very much for reporting the error.
