### ISSUE TITLE
[Feature request] DHCP with OpenVPN in TAP mode

### ISSUE THREAD

**Issue by ronneke1996** [SoftEtherVPN/SoftEtherVPN#822]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** Build from master https://github.com/SoftEtherVPN/SoftEtherVPN/commit/3842e813d6a74a8c1779c3be33e1a6d70cb242ad
**Component:** Server
**Operating system:** Ubuntu 18.04 server
**Architecture:** 64 bit

### Description

I'm using SoftEtherVPN server as an Openvpn server. Connection with an layer 3 (tun) config works fine, but when I connect with an layer 2 (tap) config I won't get an ip address. 
The server has dhcp enabled as made clear by the ip that gets leased by connection to the server with an tun config. 

**Expected behavior:**
Get an ip lease with a tap config.

**Actual behavior:**
I don't get an ip.

### Some relevant logs

When connecting with tun I do get an ifconfig push, but not with tap.

Log from tun config:
`Wed Nov 28 12:11:08 2018 PUSH: Received control message: 'PUSH_REPLY,ping 3,ping-restart 10,topology subnet,ifconfig 192.168.30.10 255.255.255.0,dhcp-option DNS 192.168.30.1,route-gateway 192.168.30.1,redirect-gateway def1'`

Log from tap config:
`Wed Nov 28 11:43:56 2018 PUSH: Received control message: 'PUSH_REPLY,ping 3,ping-restart 10'`

**Comment by davidebeatrici** [comment]
It's the intended behavior, because the operating system is supposed to be sending a DHCP request through the virtual network interface, which is what happens on Windows.
On Linux you have to do it manually, before the client times out. You could set up a script for OpenVPN to do it automatically:

`dhcp-manager.sh`
```bash
#!/bin/bash

case $script_type in

up)
	echo "Requesting IP address for ${dev} from DHCP server..."
	dhclient -v "${dev}"
	;;
down)
	echo "Releasing ${dev}'s DHCP lease..."
	dhclient -r "${dev}"
	;;
esac
```

In OpenVPN's configuration:
```
up dhcp-manager.sh
down dhcp-manager.sh
```

**Comment by ronneke1996** [comment]
Alright, after some more testing I did notice that Windows did indeed get an ip and it's only a problem on Linux. 
Though when using the standard OpenVPN server (which I plan to replace with a SoftEther one), the server does send an ip to Linux and Windows without the manual dhclient call.
Maybe this could be a new feature for SoftEther? Perhaps a setting that forces the SoftEther OpenVPN server to send out dhcp leases.

**Comment by davidebeatrici** [comment]
You're welcome!

The OpenVPN server acts as a DHCP server when you set the network in its configuration, otherwise it doesn't send the IP address because it isn't a DHCP client.

We can implement the feature in SoftEther VPN, with a client-side environment variable such as `UV_NO_DHCP` to disable it.

**Comment by davidebeatrici** [comment]
The client timing out turned out to be an OpenVPN bug, we implemented a workaround in #828.

#827 implements the desired feature, however in Layer 2 mode the DHCP lease is supposed to be requested by the client and not by an intermediary entity (the VPN server).

Do you still want the feature, now that the timeout issue is not present anymore?

**Comment by ronneke1996** [comment]
I've tested #827 and #828 and both seems to be working fine. If its up to me this feature can be merged. Again, thank you for the great work!

**Comment by davidebeatrici** [comment]
You're welcome!

> #827 implements the desired feature, however in Layer 2 mode the DHCP lease is supposed to be requested by the client and not by an intermediary entity (the VPN server).

We're probably not going to merge #827 for this reason, sorry.

**Comment by ronneke1996** [comment]
Alright, that totally understandable. I'll make a patch from your implementation for my own projects.

**Comment by davidebeatrici** [comment]
No problem.
