### ISSUE TITLE
why the file "hamcore.se2" in windows is much larger ther other platform?

### ISSUE THREAD

**Issue by stream1990** [SoftEtherVPN/SoftEtherVPN#978]
i have some question.please repley me if you have time ,thank you.
1. why the file "hamcore.se2" in windows is much larger ther other platform?
   i take the file  "hamcore.se2" from linux on replace to windows, and it works well? so why?

2. how can i make the vpnbridge for arm? i try it in android and mush error.....
    can you relase it?

**Comment by davidebeatrici** [comment]
Sorry for the huge delay.

1. `hamcore.se2` is basically an archive. It's larger on Windows because it contains extra binaries, such as drivers.
2. In theory the server and bridge components can run on Android, but it's not guaranteed due to the various limitations in Android compared to a "vanilla" Linux system.
