### ISSUE TITLE
Use LibreSSL instead of OpenSSL

### ISSUE THREAD

**Issue by 0x391F** [SoftEtherVPN/SoftEtherVPN#987]

**Comment by chipitsine** [comment]
what do you mean ?

**Comment by 0x391F** [comment]
I mean use LibreSSL for SSL-VPN, not OpenSSL.

**Comment by chipitsine** [comment]
the choice is up to you. you can use either one.

**Comment by metalefty** [comment]
Exactly, you can use it whenever you want.

**Comment by chipitsine** [comment]
@0x391F , can you explain what do you mean by opening this issue?

**Comment by metalefty** [comment]
BTW, I'm using SoftEtherVPN with LibreSSL on FreeBSD (I'm a FreeBSD developer). It works for me properly. On FreeBSD, LibreSSL is almost a drop-in replacement of OpenSSL and users can choose whichever they want: https://wiki.freebsd.org/LibreSSL

So, the subject is completely possible. You can use it if you want. I also still don't get you what does this issue mean.

**Comment by 0x391F** [comment]
https://wiki.freebsd.org/LibreSSL#LibreSSL_.28and_OpenSSL.29_Security_Vulnerabilities

**Comment by metalefty** [comment]
Yes we know.  You can use it. Just use it. Please please clarify what do you mean.

**Comment by 0x391F** [comment]
I mean use LibreSSL for SSL-VPN, not OpenSSL because LibreSSL have less bugs that we can keep away from high level vulnerability such as Heartbleed. Why it's doesn't clear?

**Comment by metalefty** [comment]
You can use LibreSSL. Feel free to use LibreSSL. What you want?

**Comment by 0x391F** [comment]
OK. I'm just hope SoftetherVPN become better, safer. Now I don't comment this issue.

**Comment by chipitsine** [comment]
@0x391F , please define next steps within this issue

**Comment by metalefty** [comment]
Just in case you don't understand how it works, SoftEtherVPN is already LibreSSL compatible. In other words, SoftEtherVPN already supports LibreSSL. Both OpenSSL and LibreSSL can be usable. 

Please understand not all people want to use LibreSSL instead of OpenSSL. SoftEtherVPN doesn't specify either to use. People who want to use OpenSSL with SoftEtherVPN can use OpenSSL, people who want to use LibreSSL with SoftEtherVPN (YOU!) can use LibreSSL. 

You repeat LibreSSL! LibreSSL! LibreSSL! Yes, you can use it. It's up to you. Go your way. But please respect each other. I'm done here.

**Comment by 0x391F** [comment]
OK. Thank you very much.
